//
//  PaintCodeStyleKit.h
//  Tackle
//
//  Created by Scott Bader on 1/11/15.
//  Copyright (c) 2015 Melody Road, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* alarmClockIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* letterTIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* arrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* clockOldTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* clockOldTwoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* stopWatchTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* calendarIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* hourglassIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* clockTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* calanderColoredTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* hourglassColoredTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* stopwatchColoredTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* checkmarkTargets;

// Drawing Methods
+ (void)drawClockComponents;
+ (void)drawCanvas1;

// Generated Images
+ (UIImage*)imageOfAlarmClockIcon;
+ (UIImage*)imageOfLetterTIcon;
+ (UIImage*)imageOfAddIcon;
+ (UIImage*)imageOfArrow;
+ (UIImage*)imageOfClockOld;
+ (UIImage*)imageOfClockOldTwo;
+ (UIImage*)imageOfStopWatch;
+ (UIImage*)imageOfCalendarIcon;
+ (UIImage*)imageOfHourglassIcon;
+ (UIImage*)imageOfClock;
+ (UIImage*)imageOfCalanderColored;
+ (UIImage*)imageOfHourglassColored;
+ (UIImage*)imageOfStopwatchColored;
+ (UIImage*)imageOfCheckmark;

@end
