//
//  PaintCodeStyleKit.m
//  Tackle
//
//  Created by Scott Bader on 1/3/15.
//  Copyright (c) 2015 Melody Road, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PaintCodeStyleKit.h"


@implementation PaintCodeStyleKit

#pragma mark Cache

static UIImage* _imageOfAlarmClockIcon = nil;
static UIImage* _imageOfLetterTIcon = nil;
static UIImage* _imageOfAddIcon = nil;
static UIImage* _imageOfArrow = nil;
static UIImage* _imageOfClock = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawAlarmClockIcon
{
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 0.393 green: 0.301 blue: 0.5 alpha: 1];

    //// Group
    {
        //// Oval-4 Drawing
        UIBezierPath* oval4Path = UIBezierPath.bezierPath;
        [oval4Path moveToPoint: CGPointMake(8.76, 2.71)];
        [oval4Path addCurveToPoint: CGPointMake(5.33, 1) controlPoint1: CGPointMake(7.97, 1.67) controlPoint2: CGPointMake(6.73, 1)];
        [oval4Path addCurveToPoint: CGPointMake(1, 5.41) controlPoint1: CGPointMake(2.94, 1) controlPoint2: CGPointMake(1, 2.98)];
        [oval4Path addCurveToPoint: CGPointMake(2.88, 9.05) controlPoint1: CGPointMake(1, 6.92) controlPoint2: CGPointMake(1.74, 8.25)];
        [oval4Path addCurveToPoint: CGPointMake(1.96, 13.75) controlPoint1: CGPointMake(2.29, 10.49) controlPoint2: CGPointMake(1.96, 12.08)];
        [oval4Path addCurveToPoint: CGPointMake(14, 26) controlPoint1: CGPointMake(1.96, 20.51) controlPoint2: CGPointMake(7.35, 26)];
        [oval4Path addCurveToPoint: CGPointMake(26.04, 13.75) controlPoint1: CGPointMake(20.65, 26) controlPoint2: CGPointMake(26.04, 20.51)];
        [oval4Path addCurveToPoint: CGPointMake(25.12, 9.05) controlPoint1: CGPointMake(26.04, 12.08) controlPoint2: CGPointMake(25.71, 10.49)];
        [oval4Path addCurveToPoint: CGPointMake(27, 5.41) controlPoint1: CGPointMake(26.26, 8.25) controlPoint2: CGPointMake(27, 6.92)];
        [oval4Path addCurveToPoint: CGPointMake(22.67, 1) controlPoint1: CGPointMake(27, 2.98) controlPoint2: CGPointMake(25.06, 1)];
        [oval4Path addCurveToPoint: CGPointMake(19.24, 2.71) controlPoint1: CGPointMake(21.27, 1) controlPoint2: CGPointMake(20.03, 1.67)];
        [oval4Path addCurveToPoint: CGPointMake(14, 1.49) controlPoint1: CGPointMake(17.66, 1.93) controlPoint2: CGPointMake(15.88, 1.49)];
        [oval4Path addCurveToPoint: CGPointMake(8.76, 2.71) controlPoint1: CGPointMake(12.12, 1.49) controlPoint2: CGPointMake(10.34, 1.93)];
        [oval4Path closePath];
        oval4Path.miterLimit = 4;

        oval4Path.lineCapStyle = kCGLineCapSquare;

        oval4Path.usesEvenOddFillRule = YES;

        [color0 setStroke];
        oval4Path.lineWidth = 2;
        [oval4Path stroke];


        //// Oval-2 Drawing
        UIBezierPath* oval2Path = UIBezierPath.bezierPath;
        [oval2Path moveToPoint: CGPointMake(15.91, 12.96)];
        [oval2Path addLineToPoint: CGPointMake(19.86, 11.83)];
        [oval2Path addCurveToPoint: CGPointMake(20.4, 12.12) controlPoint1: CGPointMake(20.1, 11.76) controlPoint2: CGPointMake(20.34, 11.89)];
        [oval2Path addCurveToPoint: CGPointMake(20.1, 12.66) controlPoint1: CGPointMake(20.47, 12.36) controlPoint2: CGPointMake(20.34, 12.6)];
        [oval2Path addLineToPoint: CGPointMake(16.16, 13.79)];
        [oval2Path addCurveToPoint: CGPointMake(16.17, 14) controlPoint1: CGPointMake(16.17, 13.86) controlPoint2: CGPointMake(16.17, 13.93)];
        [oval2Path addCurveToPoint: CGPointMake(14, 16.17) controlPoint1: CGPointMake(16.17, 15.2) controlPoint2: CGPointMake(15.2, 16.17)];
        [oval2Path addCurveToPoint: CGPointMake(12.32, 15.38) controlPoint1: CGPointMake(13.33, 16.17) controlPoint2: CGPointMake(12.72, 15.87)];
        [oval2Path addLineToPoint: CGPointMake(6.91, 18.51)];
        [oval2Path addCurveToPoint: CGPointMake(6.32, 18.35) controlPoint1: CGPointMake(6.71, 18.63) controlPoint2: CGPointMake(6.44, 18.56)];
        [oval2Path addCurveToPoint: CGPointMake(6.48, 17.76) controlPoint1: CGPointMake(6.2, 18.14) controlPoint2: CGPointMake(6.28, 17.87)];
        [oval2Path addLineToPoint: CGPointMake(11.91, 14.62)];
        [oval2Path addCurveToPoint: CGPointMake(11.83, 14) controlPoint1: CGPointMake(11.86, 14.42) controlPoint2: CGPointMake(11.83, 14.21)];
        [oval2Path addCurveToPoint: CGPointMake(14, 11.83) controlPoint1: CGPointMake(11.83, 12.8) controlPoint2: CGPointMake(12.8, 11.83)];
        [oval2Path addCurveToPoint: CGPointMake(15.91, 12.96) controlPoint1: CGPointMake(14.82, 11.83) controlPoint2: CGPointMake(15.54, 12.28)];
        [oval2Path closePath];
        [oval2Path moveToPoint: CGPointMake(14, 24)];
        [oval2Path addCurveToPoint: CGPointMake(24, 14) controlPoint1: CGPointMake(19.52, 24) controlPoint2: CGPointMake(24, 19.52)];
        [oval2Path addCurveToPoint: CGPointMake(14, 4) controlPoint1: CGPointMake(24, 8.48) controlPoint2: CGPointMake(19.52, 4)];
        [oval2Path addCurveToPoint: CGPointMake(4, 14) controlPoint1: CGPointMake(8.48, 4) controlPoint2: CGPointMake(4, 8.48)];
        [oval2Path addCurveToPoint: CGPointMake(14, 24) controlPoint1: CGPointMake(4, 19.52) controlPoint2: CGPointMake(8.48, 24)];
        [oval2Path closePath];
        oval2Path.miterLimit = 4;

        oval2Path.usesEvenOddFillRule = YES;

        [color0 setFill];
        [oval2Path fill];


        //// Oval Drawing
        UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(2, 2, 24, 24)];
        [color0 setStroke];
        ovalPath.lineWidth = 2;
        [ovalPath stroke];
    }
}

+ (void)drawLetterTIcon
{
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 0.393 green: 0.301 blue: 0.5 alpha: 1];

    //// T Drawing
    UIBezierPath* tPath = UIBezierPath.bezierPath;
    [tPath moveToPoint: CGPointMake(10.13, 17)];
    [tPath addLineToPoint: CGPointMake(10.13, 14.9)];
    [tPath addLineToPoint: CGPointMake(7.83, 15)];
    [tPath addLineToPoint: CGPointMake(7.83, 2)];
    [tPath addLineToPoint: CGPointMake(11, 2)];
    [tPath addLineToPoint: CGPointMake(10.86, 4.33)];
    [tPath addLineToPoint: CGPointMake(13, 4.33)];
    [tPath addLineToPoint: CGPointMake(13, 0)];
    [tPath addLineToPoint: CGPointMake(0, 0)];
    [tPath addLineToPoint: CGPointMake(0, 4.33)];
    [tPath addLineToPoint: CGPointMake(2.14, 4.33)];
    [tPath addLineToPoint: CGPointMake(2, 2)];
    [tPath addLineToPoint: CGPointMake(5.17, 2)];
    [tPath addLineToPoint: CGPointMake(5.17, 15)];
    [tPath addLineToPoint: CGPointMake(2.89, 14.9)];
    [tPath addLineToPoint: CGPointMake(2.89, 17)];
    [tPath addLineToPoint: CGPointMake(10.13, 17)];
    [tPath closePath];
    tPath.miterLimit = 4;

    tPath.usesEvenOddFillRule = YES;

    [color0 setFill];
    [tPath fill];
}

+ (void)drawAddIcon
{
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 0.393 green: 0.301 blue: 0.5 alpha: 1];

    //// PlusIcon Drawing
    UIBezierPath* plusIconPath = UIBezierPath.bezierPath;
    [plusIconPath moveToPoint: CGPointMake(9.78, 7.22)];
    [plusIconPath addLineToPoint: CGPointMake(9.78, 0)];
    [plusIconPath addLineToPoint: CGPointMake(7.22, 0)];
    [plusIconPath addLineToPoint: CGPointMake(7.22, 7.22)];
    [plusIconPath addLineToPoint: CGPointMake(0, 7.22)];
    [plusIconPath addLineToPoint: CGPointMake(0, 9.78)];
    [plusIconPath addLineToPoint: CGPointMake(7.22, 9.78)];
    [plusIconPath addLineToPoint: CGPointMake(7.22, 17)];
    [plusIconPath addLineToPoint: CGPointMake(9.78, 17)];
    [plusIconPath addLineToPoint: CGPointMake(9.78, 9.78)];
    [plusIconPath addLineToPoint: CGPointMake(17, 9.78)];
    [plusIconPath addLineToPoint: CGPointMake(17, 7.22)];
    [plusIconPath addLineToPoint: CGPointMake(9.78, 7.22)];
    [plusIconPath closePath];
    plusIconPath.miterLimit = 4;

    plusIconPath.usesEvenOddFillRule = YES;

    [color0 setFill];
    [plusIconPath fill];
}

+ (void)drawArrow
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.173 green: 0.173 blue: 0.173 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(10, 0)];
    [bezierPath addCurveToPoint: CGPointMake(18.66, 9.75) controlPoint1: CGPointMake(10, 0) controlPoint2: CGPointMake(18.66, 9.75)];
    [bezierPath addLineToPoint: CGPointMake(14, 9.75)];
    [bezierPath addCurveToPoint: CGPointMake(14, 80) controlPoint1: CGPointMake(14, 20.76) controlPoint2: CGPointMake(14, 80)];
    [bezierPath addLineToPoint: CGPointMake(6, 80)];
    [bezierPath addCurveToPoint: CGPointMake(6, 9.75) controlPoint1: CGPointMake(6, 80) controlPoint2: CGPointMake(6, 20.76)];
    [bezierPath addLineToPoint: CGPointMake(1.34, 9.75)];
    [bezierPath addCurveToPoint: CGPointMake(10, 0) controlPoint1: CGPointMake(1.34, 9.75) controlPoint2: CGPointMake(10, 0)];
    [bezierPath addLineToPoint: CGPointMake(10, 0)];
    [bezierPath closePath];
    [color setFill];
    [bezierPath fill];
}

+ (void)drawClock
{
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 0.393 green: 0.301 blue: 0.5 alpha: 1];

    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(1, 1, 25, 25)];
    [color0 setStroke];
    ovalPath.lineWidth = 1;
    [ovalPath stroke];


    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(12.38, 2.05)];
    [bezierPath addCurveToPoint: CGPointMake(12.17, 2.08) controlPoint1: CGPointMake(12.32, 2.06) controlPoint2: CGPointMake(12.22, 2.07)];
    [bezierPath addCurveToPoint: CGPointMake(12.2, 2.58) controlPoint1: CGPointMake(12.15, 2.09) controlPoint2: CGPointMake(12.17, 2.26)];
    [bezierPath addLineToPoint: CGPointMake(12.46, 2.55)];
    [bezierPath addCurveToPoint: CGPointMake(12.38, 2.06) controlPoint1: CGPointMake(12.42, 2.23) controlPoint2: CGPointMake(12.39, 2.05)];
    [bezierPath addLineToPoint: CGPointMake(12.38, 2.05)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(11.26, 2.22)];
    [bezierPath addLineToPoint: CGPointMake(10.96, 2.28)];
    [bezierPath addCurveToPoint: CGPointMake(11.07, 2.77) controlPoint1: CGPointMake(10.96, 2.28) controlPoint2: CGPointMake(11, 2.46)];
    [bezierPath addCurveToPoint: CGPointMake(11.36, 2.71) controlPoint1: CGPointMake(11.16, 2.75) controlPoint2: CGPointMake(11.26, 2.73)];
    [bezierPath addCurveToPoint: CGPointMake(11.26, 2.22) controlPoint1: CGPointMake(11.29, 2.39) controlPoint2: CGPointMake(11.26, 2.22)];
    [bezierPath addLineToPoint: CGPointMake(11.26, 2.22)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(15.74, 2.22)];
    [bezierPath addCurveToPoint: CGPointMake(15.64, 2.71) controlPoint1: CGPointMake(15.74, 2.25) controlPoint2: CGPointMake(15.7, 2.42)];
    [bezierPath addCurveToPoint: CGPointMake(15.93, 2.77) controlPoint1: CGPointMake(15.74, 2.73) controlPoint2: CGPointMake(15.84, 2.75)];
    [bezierPath addCurveToPoint: CGPointMake(16.04, 2.28) controlPoint1: CGPointMake(16, 2.46) controlPoint2: CGPointMake(16.04, 2.28)];
    [bezierPath addCurveToPoint: CGPointMake(15.75, 2.22) controlPoint1: CGPointMake(16.04, 2.28) controlPoint2: CGPointMake(15.74, 2.22)];
    [bezierPath addLineToPoint: CGPointMake(15.74, 2.22)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(10.09, 2.52)];
    [bezierPath addLineToPoint: CGPointMake(9.8, 2.61)];
    [bezierPath addCurveToPoint: CGPointMake(9.96, 3.08) controlPoint1: CGPointMake(9.8, 2.61) controlPoint2: CGPointMake(9.86, 2.78)];
    [bezierPath addCurveToPoint: CGPointMake(10.24, 2.99) controlPoint1: CGPointMake(10.05, 3.05) controlPoint2: CGPointMake(10.15, 3.02)];
    [bezierPath addCurveToPoint: CGPointMake(10.09, 2.52) controlPoint1: CGPointMake(10.14, 2.68) controlPoint2: CGPointMake(10.09, 2.52)];
    [bezierPath addLineToPoint: CGPointMake(10.09, 2.52)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(16.91, 2.52)];
    [bezierPath addCurveToPoint: CGPointMake(16.76, 2.99) controlPoint1: CGPointMake(16.91, 2.52) controlPoint2: CGPointMake(16.86, 2.68)];
    [bezierPath addCurveToPoint: CGPointMake(17.04, 3.08) controlPoint1: CGPointMake(16.85, 3.02) controlPoint2: CGPointMake(16.95, 3.05)];
    [bezierPath addCurveToPoint: CGPointMake(17.2, 2.61) controlPoint1: CGPointMake(17.14, 2.78) controlPoint2: CGPointMake(17.2, 2.61)];
    [bezierPath addCurveToPoint: CGPointMake(16.91, 2.52) controlPoint1: CGPointMake(17.2, 2.61) controlPoint2: CGPointMake(16.91, 2.52)];
    [bezierPath addLineToPoint: CGPointMake(16.91, 2.52)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(8.95, 2.94)];
    [bezierPath addCurveToPoint: CGPointMake(8.69, 3.06) controlPoint1: CGPointMake(8.91, 2.96) controlPoint2: CGPointMake(8.69, 3.06)];
    [bezierPath addCurveToPoint: CGPointMake(8.89, 3.51) controlPoint1: CGPointMake(8.69, 3.06) controlPoint2: CGPointMake(8.76, 3.22)];
    [bezierPath addCurveToPoint: CGPointMake(9.16, 3.39) controlPoint1: CGPointMake(8.98, 3.47) controlPoint2: CGPointMake(9.07, 3.43)];
    [bezierPath addCurveToPoint: CGPointMake(8.95, 2.94) controlPoint1: CGPointMake(9.03, 3.1) controlPoint2: CGPointMake(8.95, 2.94)];
    [bezierPath addLineToPoint: CGPointMake(8.95, 2.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(18.04, 2.94)];
    [bezierPath addCurveToPoint: CGPointMake(17.84, 3.39) controlPoint1: CGPointMake(18.02, 2.97) controlPoint2: CGPointMake(17.95, 3.13)];
    [bezierPath addCurveToPoint: CGPointMake(18.11, 3.51) controlPoint1: CGPointMake(17.93, 3.43) controlPoint2: CGPointMake(18.02, 3.47)];
    [bezierPath addCurveToPoint: CGPointMake(18.31, 3.06) controlPoint1: CGPointMake(18.24, 3.22) controlPoint2: CGPointMake(18.31, 3.06)];
    [bezierPath addCurveToPoint: CGPointMake(18.04, 2.94) controlPoint1: CGPointMake(18.31, 3.06) controlPoint2: CGPointMake(18.04, 2.93)];
    [bezierPath addLineToPoint: CGPointMake(18.04, 2.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(13.61, 2)];
    [bezierPath addCurveToPoint: CGPointMake(13.5, 2) controlPoint1: CGPointMake(13.57, 2) controlPoint2: CGPointMake(13.54, 2)];
    [bezierPath addCurveToPoint: CGPointMake(13.25, 2) controlPoint1: CGPointMake(13.46, 2) controlPoint2: CGPointMake(13.25, 2)];
    [bezierPath addCurveToPoint: CGPointMake(13.25, 3) controlPoint1: CGPointMake(13.25, 2.05) controlPoint2: CGPointMake(13.25, 2.41)];
    [bezierPath addLineToPoint: CGPointMake(13.5, 3)];
    [bezierPath addLineToPoint: CGPointMake(13.75, 3)];
    [bezierPath addCurveToPoint: CGPointMake(13.75, 2) controlPoint1: CGPointMake(13.75, 2.39) controlPoint2: CGPointMake(13.75, 2.03)];
    [bezierPath addCurveToPoint: CGPointMake(14.56, 2.05) controlPoint1: CGPointMake(14.02, 2.01) controlPoint2: CGPointMake(14.29, 2.02)];
    [bezierPath addCurveToPoint: CGPointMake(14.5, 2.54) controlPoint1: CGPointMake(14.55, 2.07) controlPoint2: CGPointMake(14.53, 2.24)];
    [bezierPath addCurveToPoint: CGPointMake(14.8, 2.58) controlPoint1: CGPointMake(14.6, 2.55) controlPoint2: CGPointMake(14.7, 2.56)];
    [bezierPath addCurveToPoint: CGPointMake(14.85, 2.08) controlPoint1: CGPointMake(14.83, 2.27) controlPoint2: CGPointMake(14.85, 2.09)];
    [bezierPath addCurveToPoint: CGPointMake(14.62, 2.05) controlPoint1: CGPointMake(14.72, 2.07) controlPoint2: CGPointMake(14.67, 2.06)];
    [bezierPath addLineToPoint: CGPointMake(14.62, 2.05)];
    [bezierPath addLineToPoint: CGPointMake(14.77, 2.07)];
    [bezierPath addLineToPoint: CGPointMake(14.85, 2.08)];
    [bezierPath addCurveToPoint: CGPointMake(15.75, 2.22) controlPoint1: CGPointMake(15.15, 2.11) controlPoint2: CGPointMake(15.45, 2.16)];
    [bezierPath addCurveToPoint: CGPointMake(16.04, 2.28) controlPoint1: CGPointMake(15.74, 2.22) controlPoint2: CGPointMake(16.04, 2.28)];
    [bezierPath addCurveToPoint: CGPointMake(16.91, 2.52) controlPoint1: CGPointMake(16.04, 2.28) controlPoint2: CGPointMake(16.91, 2.52)];
    [bezierPath addCurveToPoint: CGPointMake(17.2, 2.61) controlPoint1: CGPointMake(16.91, 2.52) controlPoint2: CGPointMake(17.2, 2.61)];
    [bezierPath addCurveToPoint: CGPointMake(18.04, 2.93) controlPoint1: CGPointMake(17.2, 2.61) controlPoint2: CGPointMake(18.04, 2.93)];
    [bezierPath addLineToPoint: CGPointMake(18.3, 3.05)];
    [bezierPath addLineToPoint: CGPointMake(19.03, 3.42)];
    [bezierPath addCurveToPoint: CGPointMake(19.39, 3.62) controlPoint1: CGPointMake(19.15, 3.48) controlPoint2: CGPointMake(19.27, 3.55)];
    [bezierPath addCurveToPoint: CGPointMake(19.03, 3.42) controlPoint1: CGPointMake(19.26, 3.55) controlPoint2: CGPointMake(19.03, 3.42)];
    [bezierPath addCurveToPoint: CGPointMake(18.53, 4.28) controlPoint1: CGPointMake(19.02, 3.43) controlPoint2: CGPointMake(18.96, 3.54)];
    [bezierPath addCurveToPoint: CGPointMake(18.97, 4.53) controlPoint1: CGPointMake(18.68, 4.36) controlPoint2: CGPointMake(18.82, 4.45)];
    [bezierPath addCurveToPoint: CGPointMake(19.47, 3.67) controlPoint1: CGPointMake(19.27, 4.01) controlPoint2: CGPointMake(19.45, 3.69)];
    [bezierPath addCurveToPoint: CGPointMake(20.14, 4.11) controlPoint1: CGPointMake(19.7, 3.81) controlPoint2: CGPointMake(19.92, 3.95)];
    [bezierPath addLineToPoint: CGPointMake(20.33, 4.25)];
    [bezierPath addCurveToPoint: CGPointMake(20.14, 4.12) controlPoint1: CGPointMake(20.26, 4.2) controlPoint2: CGPointMake(20.14, 4.11)];
    [bezierPath addCurveToPoint: CGPointMake(19.84, 4.51) controlPoint1: CGPointMake(20.11, 4.15) controlPoint2: CGPointMake(20.01, 4.28)];
    [bezierPath addCurveToPoint: CGPointMake(20.09, 4.69) controlPoint1: CGPointMake(19.93, 4.57) controlPoint2: CGPointMake(20.01, 4.63)];
    [bezierPath addCurveToPoint: CGPointMake(20.38, 4.28) controlPoint1: CGPointMake(20.27, 4.43) controlPoint2: CGPointMake(20.38, 4.29)];
    [bezierPath addCurveToPoint: CGPointMake(21.08, 4.85) controlPoint1: CGPointMake(20.62, 4.47) controlPoint2: CGPointMake(20.86, 4.66)];
    [bezierPath addCurveToPoint: CGPointMake(20.75, 5.23) controlPoint1: CGPointMake(21.07, 4.87) controlPoint2: CGPointMake(20.95, 5)];
    [bezierPath addCurveToPoint: CGPointMake(20.97, 5.43) controlPoint1: CGPointMake(20.82, 5.29) controlPoint2: CGPointMake(20.9, 5.36)];
    [bezierPath addCurveToPoint: CGPointMake(21.31, 5.06) controlPoint1: CGPointMake(21.18, 5.2) controlPoint2: CGPointMake(21.29, 5.07)];
    [bezierPath addCurveToPoint: CGPointMake(21.95, 5.7) controlPoint1: CGPointMake(21.53, 5.26) controlPoint2: CGPointMake(21.74, 5.47)];
    [bezierPath addLineToPoint: CGPointMake(22.07, 5.83)];
    [bezierPath addCurveToPoint: CGPointMake(21.94, 5.7) controlPoint1: CGPointMake(22.01, 5.77) controlPoint2: CGPointMake(21.94, 5.7)];
    [bezierPath addCurveToPoint: CGPointMake(21.57, 6.03) controlPoint1: CGPointMake(21.9, 5.73) controlPoint2: CGPointMake(21.78, 5.84)];
    [bezierPath addCurveToPoint: CGPointMake(21.77, 6.25) controlPoint1: CGPointMake(21.64, 6.1) controlPoint2: CGPointMake(21.71, 6.18)];
    [bezierPath addCurveToPoint: CGPointMake(22.15, 5.92) controlPoint1: CGPointMake(22, 6.05) controlPoint2: CGPointMake(22.13, 5.93)];
    [bezierPath addCurveToPoint: CGPointMake(22.72, 6.62) controlPoint1: CGPointMake(22.35, 6.14) controlPoint2: CGPointMake(22.54, 6.38)];
    [bezierPath addLineToPoint: CGPointMake(22.88, 6.85)];
    [bezierPath addCurveToPoint: CGPointMake(22.71, 6.63) controlPoint1: CGPointMake(22.85, 6.81) controlPoint2: CGPointMake(22.71, 6.62)];
    [bezierPath addCurveToPoint: CGPointMake(22.31, 6.91) controlPoint1: CGPointMake(22.67, 6.65) controlPoint2: CGPointMake(22.53, 6.75)];
    [bezierPath addCurveToPoint: CGPointMake(22.49, 7.16) controlPoint1: CGPointMake(22.37, 6.99) controlPoint2: CGPointMake(22.43, 7.07)];
    [bezierPath addCurveToPoint: CGPointMake(22.89, 6.86) controlPoint1: CGPointMake(22.74, 6.97) controlPoint2: CGPointMake(22.89, 6.87)];
    [bezierPath addCurveToPoint: CGPointMake(23.33, 7.53) controlPoint1: CGPointMake(23.05, 7.08) controlPoint2: CGPointMake(23.19, 7.3)];
    [bezierPath addCurveToPoint: CGPointMake(22.47, 8.03) controlPoint1: CGPointMake(23.33, 7.54) controlPoint2: CGPointMake(23.25, 7.58)];
    [bezierPath addCurveToPoint: CGPointMake(22.72, 8.47) controlPoint1: CGPointMake(22.55, 8.18) controlPoint2: CGPointMake(22.64, 8.32)];
    [bezierPath addCurveToPoint: CGPointMake(23.58, 7.97) controlPoint1: CGPointMake(23.24, 8.16) controlPoint2: CGPointMake(23.56, 7.98)];
    [bezierPath addCurveToPoint: CGPointMake(23.95, 8.69) controlPoint1: CGPointMake(23.71, 8.2) controlPoint2: CGPointMake(23.83, 8.44)];
    [bezierPath addCurveToPoint: CGPointMake(24.07, 8.96) controlPoint1: CGPointMake(23.94, 8.69) controlPoint2: CGPointMake(24.07, 8.96)];
    [bezierPath addCurveToPoint: CGPointMake(24.39, 9.81) controlPoint1: CGPointMake(24.07, 8.96) controlPoint2: CGPointMake(24.39, 9.81)];
    [bezierPath addCurveToPoint: CGPointMake(24.48, 10.09) controlPoint1: CGPointMake(24.39, 9.8) controlPoint2: CGPointMake(24.48, 10.09)];
    [bezierPath addCurveToPoint: CGPointMake(24.72, 10.97) controlPoint1: CGPointMake(24.49, 10.09) controlPoint2: CGPointMake(24.72, 10.97)];
    [bezierPath addCurveToPoint: CGPointMake(24.78, 11.26) controlPoint1: CGPointMake(24.72, 10.96) controlPoint2: CGPointMake(24.78, 11.26)];
    [bezierPath addCurveToPoint: CGPointMake(24.92, 12.15) controlPoint1: CGPointMake(24.78, 11.26) controlPoint2: CGPointMake(24.92, 12.15)];
    [bezierPath addLineToPoint: CGPointMake(24.93, 12.23)];
    [bezierPath addLineToPoint: CGPointMake(24.95, 12.38)];
    [bezierPath addCurveToPoint: CGPointMake(24.93, 12.23) controlPoint1: CGPointMake(24.94, 12.33) controlPoint2: CGPointMake(24.93, 12.28)];
    [bezierPath addCurveToPoint: CGPointMake(24.42, 12.2) controlPoint1: CGPointMake(24.91, 12.15) controlPoint2: CGPointMake(24.73, 12.17)];
    [bezierPath addCurveToPoint: CGPointMake(24.45, 12.5) controlPoint1: CGPointMake(24.44, 12.3) controlPoint2: CGPointMake(24.45, 12.4)];
    [bezierPath addCurveToPoint: CGPointMake(24.95, 12.45) controlPoint1: CGPointMake(24.76, 12.47) controlPoint2: CGPointMake(24.94, 12.45)];
    [bezierPath addCurveToPoint: CGPointMake(25, 13.25) controlPoint1: CGPointMake(24.98, 12.71) controlPoint2: CGPointMake(24.99, 12.98)];
    [bezierPath addCurveToPoint: CGPointMake(24, 13.25) controlPoint1: CGPointMake(24.96, 13.25) controlPoint2: CGPointMake(24.58, 13.25)];
    [bezierPath addLineToPoint: CGPointMake(24, 13.5)];
    [bezierPath addLineToPoint: CGPointMake(24, 13.75)];
    [bezierPath addLineToPoint: CGPointMake(25, 13.75)];
    [bezierPath addCurveToPoint: CGPointMake(24.95, 14.55) controlPoint1: CGPointMake(24.99, 14.02) controlPoint2: CGPointMake(24.98, 14.29)];
    [bezierPath addCurveToPoint: CGPointMake(24.46, 14.5) controlPoint1: CGPointMake(24.86, 14.54) controlPoint2: CGPointMake(24.7, 14.53)];
    [bezierPath addCurveToPoint: CGPointMake(24.42, 14.8) controlPoint1: CGPointMake(24.45, 14.6) controlPoint2: CGPointMake(24.44, 14.7)];
    [bezierPath addCurveToPoint: CGPointMake(24.92, 14.85) controlPoint1: CGPointMake(24.73, 14.83) controlPoint2: CGPointMake(24.91, 14.85)];
    [bezierPath addCurveToPoint: CGPointMake(24.92, 14.55) controlPoint1: CGPointMake(24.93, 14.73) controlPoint2: CGPointMake(24.95, 14.55)];
    [bezierPath addLineToPoint: CGPointMake(24.93, 14.81)];
    [bezierPath addCurveToPoint: CGPointMake(24.78, 15.74) controlPoint1: CGPointMake(24.89, 15.15) controlPoint2: CGPointMake(24.84, 15.45)];
    [bezierPath addCurveToPoint: CGPointMake(24.72, 16.04) controlPoint1: CGPointMake(24.78, 15.74) controlPoint2: CGPointMake(24.72, 16.04)];
    [bezierPath addCurveToPoint: CGPointMake(24.49, 16.91) controlPoint1: CGPointMake(24.72, 16.04) controlPoint2: CGPointMake(24.49, 16.91)];
    [bezierPath addCurveToPoint: CGPointMake(24.39, 17.2) controlPoint1: CGPointMake(24.48, 16.91) controlPoint2: CGPointMake(24.39, 17.2)];
    [bezierPath addCurveToPoint: CGPointMake(24.07, 18.04) controlPoint1: CGPointMake(24.39, 17.2) controlPoint2: CGPointMake(24.07, 18.04)];
    [bezierPath addLineToPoint: CGPointMake(23.96, 18.29)];
    [bezierPath addLineToPoint: CGPointMake(23.58, 19.03)];
    [bezierPath addCurveToPoint: CGPointMake(22.72, 18.53) controlPoint1: CGPointMake(23.45, 18.96) controlPoint2: CGPointMake(23.15, 18.78)];
    [bezierPath addCurveToPoint: CGPointMake(22.47, 18.97) controlPoint1: CGPointMake(22.64, 18.68) controlPoint2: CGPointMake(22.55, 18.82)];
    [bezierPath addLineToPoint: CGPointMake(22.87, 19.2)];
    [bezierPath addCurveToPoint: CGPointMake(23.33, 19.47) controlPoint1: CGPointMake(23.02, 19.29) controlPoint2: CGPointMake(23.18, 19.38)];
    [bezierPath addCurveToPoint: CGPointMake(22.89, 20.14) controlPoint1: CGPointMake(23.19, 19.7) controlPoint2: CGPointMake(23.05, 19.92)];
    [bezierPath addCurveToPoint: CGPointMake(22.49, 19.84) controlPoint1: CGPointMake(22.81, 20.08) controlPoint2: CGPointMake(22.68, 19.99)];
    [bezierPath addCurveToPoint: CGPointMake(22.31, 20.09) controlPoint1: CGPointMake(22.43, 19.93) controlPoint2: CGPointMake(22.37, 20.01)];
    [bezierPath addCurveToPoint: CGPointMake(22.72, 20.38) controlPoint1: CGPointMake(22.57, 20.27) controlPoint2: CGPointMake(22.71, 20.38)];
    [bezierPath addCurveToPoint: CGPointMake(22.15, 21.08) controlPoint1: CGPointMake(22.53, 20.62) controlPoint2: CGPointMake(22.34, 20.86)];
    [bezierPath addCurveToPoint: CGPointMake(21.77, 20.75) controlPoint1: CGPointMake(22.07, 21.02) controlPoint2: CGPointMake(21.95, 20.91)];
    [bezierPath addCurveToPoint: CGPointMake(21.57, 20.97) controlPoint1: CGPointMake(21.71, 20.82) controlPoint2: CGPointMake(21.64, 20.9)];
    [bezierPath addCurveToPoint: CGPointMake(21.94, 21.31) controlPoint1: CGPointMake(21.8, 21.18) controlPoint2: CGPointMake(21.93, 21.29)];
    [bezierPath addCurveToPoint: CGPointMake(21.31, 21.95) controlPoint1: CGPointMake(21.74, 21.53) controlPoint2: CGPointMake(21.53, 21.74)];
    [bezierPath addCurveToPoint: CGPointMake(20.97, 21.57) controlPoint1: CGPointMake(21.24, 21.87) controlPoint2: CGPointMake(21.13, 21.75)];
    [bezierPath addCurveToPoint: CGPointMake(20.75, 21.77) controlPoint1: CGPointMake(20.9, 21.64) controlPoint2: CGPointMake(20.82, 21.71)];
    [bezierPath addCurveToPoint: CGPointMake(21.08, 22.15) controlPoint1: CGPointMake(20.95, 22) controlPoint2: CGPointMake(21.07, 22.13)];
    [bezierPath addCurveToPoint: CGPointMake(20.38, 22.72) controlPoint1: CGPointMake(20.86, 22.34) controlPoint2: CGPointMake(20.62, 22.53)];
    [bezierPath addCurveToPoint: CGPointMake(20.09, 22.31) controlPoint1: CGPointMake(20.32, 22.64) controlPoint2: CGPointMake(20.23, 22.51)];
    [bezierPath addCurveToPoint: CGPointMake(19.84, 22.49) controlPoint1: CGPointMake(20.01, 22.37) controlPoint2: CGPointMake(19.93, 22.43)];
    [bezierPath addCurveToPoint: CGPointMake(20.14, 22.89) controlPoint1: CGPointMake(20.03, 22.74) controlPoint2: CGPointMake(20.13, 22.89)];
    [bezierPath addCurveToPoint: CGPointMake(19.47, 23.33) controlPoint1: CGPointMake(19.92, 23.05) controlPoint2: CGPointMake(19.7, 23.19)];
    [bezierPath addCurveToPoint: CGPointMake(18.97, 22.47) controlPoint1: CGPointMake(19.41, 23.23) controlPoint2: CGPointMake(19.29, 23.04)];
    [bezierPath addCurveToPoint: CGPointMake(18.53, 22.72) controlPoint1: CGPointMake(18.82, 22.55) controlPoint2: CGPointMake(18.68, 22.64)];
    [bezierPath addCurveToPoint: CGPointMake(19.03, 23.58) controlPoint1: CGPointMake(18.84, 23.24) controlPoint2: CGPointMake(19.02, 23.56)];
    [bezierPath addCurveToPoint: CGPointMake(18.32, 23.95) controlPoint1: CGPointMake(18.8, 23.71) controlPoint2: CGPointMake(18.56, 23.83)];
    [bezierPath addCurveToPoint: CGPointMake(18.04, 24.07) controlPoint1: CGPointMake(18.31, 23.94) controlPoint2: CGPointMake(18.04, 24.07)];
    [bezierPath addCurveToPoint: CGPointMake(17.2, 24.39) controlPoint1: CGPointMake(18.04, 24.07) controlPoint2: CGPointMake(17.2, 24.39)];
    [bezierPath addCurveToPoint: CGPointMake(16.91, 24.48) controlPoint1: CGPointMake(17.2, 24.39) controlPoint2: CGPointMake(16.91, 24.48)];
    [bezierPath addCurveToPoint: CGPointMake(16.04, 24.72) controlPoint1: CGPointMake(16.91, 24.49) controlPoint2: CGPointMake(16.04, 24.72)];
    [bezierPath addCurveToPoint: CGPointMake(15.74, 24.78) controlPoint1: CGPointMake(16.04, 24.72) controlPoint2: CGPointMake(15.74, 24.78)];
    [bezierPath addCurveToPoint: CGPointMake(14.85, 24.92) controlPoint1: CGPointMake(15.75, 24.78) controlPoint2: CGPointMake(14.85, 24.92)];
    [bezierPath addLineToPoint: CGPointMake(14.6, 24.95)];
    [bezierPath addCurveToPoint: CGPointMake(14.85, 24.89) controlPoint1: CGPointMake(14.68, 24.94) controlPoint2: CGPointMake(14.85, 24.91)];
    [bezierPath addCurveToPoint: CGPointMake(14.8, 24.42) controlPoint1: CGPointMake(14.84, 24.82) controlPoint2: CGPointMake(14.82, 24.66)];
    [bezierPath addCurveToPoint: CGPointMake(14.5, 24.45) controlPoint1: CGPointMake(14.7, 24.44) controlPoint2: CGPointMake(14.6, 24.45)];
    [bezierPath addCurveToPoint: CGPointMake(14.55, 24.95) controlPoint1: CGPointMake(14.53, 24.76) controlPoint2: CGPointMake(14.55, 24.94)];
    [bezierPath addCurveToPoint: CGPointMake(13.75, 25) controlPoint1: CGPointMake(14.29, 24.98) controlPoint2: CGPointMake(14.02, 24.99)];
    [bezierPath addCurveToPoint: CGPointMake(13.75, 24) controlPoint1: CGPointMake(13.75, 24.96) controlPoint2: CGPointMake(13.75, 24.6)];
    [bezierPath addLineToPoint: CGPointMake(13.5, 24)];
    [bezierPath addLineToPoint: CGPointMake(13.25, 24)];
    [bezierPath addCurveToPoint: CGPointMake(13.25, 25) controlPoint1: CGPointMake(13.25, 24.6) controlPoint2: CGPointMake(13.25, 24.96)];
    [bezierPath addCurveToPoint: CGPointMake(12.45, 24.95) controlPoint1: CGPointMake(12.98, 24.99) controlPoint2: CGPointMake(12.71, 24.98)];
    [bezierPath addCurveToPoint: CGPointMake(12.5, 24.46) controlPoint1: CGPointMake(12.45, 24.94) controlPoint2: CGPointMake(12.47, 24.76)];
    [bezierPath addCurveToPoint: CGPointMake(12.2, 24.42) controlPoint1: CGPointMake(12.4, 24.45) controlPoint2: CGPointMake(12.3, 24.44)];
    [bezierPath addCurveToPoint: CGPointMake(12.15, 24.92) controlPoint1: CGPointMake(12.17, 24.73) controlPoint2: CGPointMake(12.15, 24.91)];
    [bezierPath addCurveToPoint: CGPointMake(12.38, 24.95) controlPoint1: CGPointMake(12.28, 24.93) controlPoint2: CGPointMake(12.33, 24.94)];
    [bezierPath addLineToPoint: CGPointMake(12.23, 24.93)];
    [bezierPath addLineToPoint: CGPointMake(12.15, 24.92)];
    [bezierPath addLineToPoint: CGPointMake(8.94, 24.06)];
    [bezierPath addLineToPoint: CGPointMake(8.69, 23.95)];
    [bezierPath addLineToPoint: CGPointMake(7.97, 23.58)];
    [bezierPath addCurveToPoint: CGPointMake(8.47, 22.72) controlPoint1: CGPointMake(7.98, 23.56) controlPoint2: CGPointMake(8.17, 23.23)];
    [bezierPath addCurveToPoint: CGPointMake(8.03, 22.47) controlPoint1: CGPointMake(8.32, 22.64) controlPoint2: CGPointMake(8.18, 22.55)];
    [bezierPath addCurveToPoint: CGPointMake(7.53, 23.33) controlPoint1: CGPointMake(7.87, 22.75) controlPoint2: CGPointMake(7.7, 23.04)];
    [bezierPath addCurveToPoint: CGPointMake(6.86, 22.89) controlPoint1: CGPointMake(7.3, 23.19) controlPoint2: CGPointMake(7.08, 23.05)];
    [bezierPath addCurveToPoint: CGPointMake(7.16, 22.49) controlPoint1: CGPointMake(6.87, 22.89) controlPoint2: CGPointMake(6.97, 22.74)];
    [bezierPath addCurveToPoint: CGPointMake(6.91, 22.31) controlPoint1: CGPointMake(7.07, 22.43) controlPoint2: CGPointMake(6.99, 22.37)];
    [bezierPath addCurveToPoint: CGPointMake(6.62, 22.72) controlPoint1: CGPointMake(6.73, 22.57) controlPoint2: CGPointMake(6.62, 22.71)];
    [bezierPath addCurveToPoint: CGPointMake(5.92, 22.15) controlPoint1: CGPointMake(6.38, 22.53) controlPoint2: CGPointMake(6.14, 22.34)];
    [bezierPath addCurveToPoint: CGPointMake(6.25, 21.77) controlPoint1: CGPointMake(5.93, 22.13) controlPoint2: CGPointMake(6.05, 22)];
    [bezierPath addCurveToPoint: CGPointMake(6.03, 21.57) controlPoint1: CGPointMake(6.18, 21.71) controlPoint2: CGPointMake(6.1, 21.64)];
    [bezierPath addCurveToPoint: CGPointMake(5.69, 21.94) controlPoint1: CGPointMake(5.82, 21.8) controlPoint2: CGPointMake(5.71, 21.93)];
    [bezierPath addCurveToPoint: CGPointMake(5.05, 21.31) controlPoint1: CGPointMake(5.47, 21.74) controlPoint2: CGPointMake(5.26, 21.53)];
    [bezierPath addCurveToPoint: CGPointMake(5.43, 20.97) controlPoint1: CGPointMake(5.07, 21.29) controlPoint2: CGPointMake(5.2, 21.18)];
    [bezierPath addCurveToPoint: CGPointMake(5.23, 20.75) controlPoint1: CGPointMake(5.36, 20.9) controlPoint2: CGPointMake(5.29, 20.82)];
    [bezierPath addCurveToPoint: CGPointMake(4.85, 21.08) controlPoint1: CGPointMake(5, 20.95) controlPoint2: CGPointMake(4.87, 21.07)];
    [bezierPath addCurveToPoint: CGPointMake(4.28, 20.38) controlPoint1: CGPointMake(4.66, 20.86) controlPoint2: CGPointMake(4.47, 20.62)];
    [bezierPath addCurveToPoint: CGPointMake(4.69, 20.09) controlPoint1: CGPointMake(4.29, 20.38) controlPoint2: CGPointMake(4.43, 20.27)];
    [bezierPath addCurveToPoint: CGPointMake(4.51, 19.84) controlPoint1: CGPointMake(4.63, 20.01) controlPoint2: CGPointMake(4.57, 19.93)];
    [bezierPath addCurveToPoint: CGPointMake(4.11, 20.14) controlPoint1: CGPointMake(4.26, 20.03) controlPoint2: CGPointMake(4.11, 20.13)];
    [bezierPath addCurveToPoint: CGPointMake(3.67, 19.47) controlPoint1: CGPointMake(3.95, 19.92) controlPoint2: CGPointMake(3.81, 19.7)];
    [bezierPath addCurveToPoint: CGPointMake(4.53, 18.97) controlPoint1: CGPointMake(3.69, 19.45) controlPoint2: CGPointMake(4.02, 19.26)];
    [bezierPath addCurveToPoint: CGPointMake(4.28, 18.53) controlPoint1: CGPointMake(4.45, 18.82) controlPoint2: CGPointMake(4.36, 18.68)];
    [bezierPath addCurveToPoint: CGPointMake(3.42, 19.03) controlPoint1: CGPointMake(4, 18.7) controlPoint2: CGPointMake(3.71, 18.86)];
    [bezierPath addLineToPoint: CGPointMake(3.05, 18.31)];
    [bezierPath addLineToPoint: CGPointMake(2.94, 18.06)];
    [bezierPath addLineToPoint: CGPointMake(2.08, 14.85)];
    [bezierPath addLineToPoint: CGPointMake(2.07, 14.77)];
    [bezierPath addLineToPoint: CGPointMake(2.05, 14.62)];
    [bezierPath addCurveToPoint: CGPointMake(2.07, 14.77) controlPoint1: CGPointMake(2.06, 14.67) controlPoint2: CGPointMake(2.07, 14.72)];
    [bezierPath addCurveToPoint: CGPointMake(2.58, 14.8) controlPoint1: CGPointMake(2.09, 14.85) controlPoint2: CGPointMake(2.27, 14.83)];
    [bezierPath addCurveToPoint: CGPointMake(2.55, 14.5) controlPoint1: CGPointMake(2.56, 14.7) controlPoint2: CGPointMake(2.55, 14.6)];
    [bezierPath addCurveToPoint: CGPointMake(2.05, 14.55) controlPoint1: CGPointMake(2.24, 14.53) controlPoint2: CGPointMake(2.06, 14.55)];
    [bezierPath addCurveToPoint: CGPointMake(2, 13.75) controlPoint1: CGPointMake(2.02, 14.29) controlPoint2: CGPointMake(2.01, 14.02)];
    [bezierPath addCurveToPoint: CGPointMake(3, 13.75) controlPoint1: CGPointMake(2.04, 13.75) controlPoint2: CGPointMake(2.42, 13.75)];
    [bezierPath addLineToPoint: CGPointMake(3, 13.5)];
    [bezierPath addLineToPoint: CGPointMake(3, 13.25)];
    [bezierPath addLineToPoint: CGPointMake(2, 13.25)];
    [bezierPath addCurveToPoint: CGPointMake(2.05, 12.45) controlPoint1: CGPointMake(2.01, 12.98) controlPoint2: CGPointMake(2.02, 12.71)];
    [bezierPath addCurveToPoint: CGPointMake(2.54, 12.5) controlPoint1: CGPointMake(2.06, 12.45) controlPoint2: CGPointMake(2.23, 12.47)];
    [bezierPath addCurveToPoint: CGPointMake(2.58, 12.2) controlPoint1: CGPointMake(2.55, 12.4) controlPoint2: CGPointMake(2.56, 12.3)];
    [bezierPath addCurveToPoint: CGPointMake(2.08, 12.15) controlPoint1: CGPointMake(2.26, 12.17) controlPoint2: CGPointMake(2.08, 12.15)];
    [bezierPath addCurveToPoint: CGPointMake(2.05, 12.41) controlPoint1: CGPointMake(2.08, 12.18) controlPoint2: CGPointMake(2.06, 12.33)];
    [bezierPath addLineToPoint: CGPointMake(2.08, 12.15)];
    [bezierPath addCurveToPoint: CGPointMake(2.22, 11.25) controlPoint1: CGPointMake(2.08, 12.15) controlPoint2: CGPointMake(2.22, 11.25)];
    [bezierPath addCurveToPoint: CGPointMake(2.28, 10.96) controlPoint1: CGPointMake(2.22, 11.26) controlPoint2: CGPointMake(2.28, 10.96)];
    [bezierPath addCurveToPoint: CGPointMake(2.51, 10.09) controlPoint1: CGPointMake(2.28, 10.96) controlPoint2: CGPointMake(2.51, 10.09)];
    [bezierPath addCurveToPoint: CGPointMake(2.61, 9.8) controlPoint1: CGPointMake(2.52, 10.09) controlPoint2: CGPointMake(2.61, 9.8)];
    [bezierPath addCurveToPoint: CGPointMake(2.93, 8.96) controlPoint1: CGPointMake(2.61, 9.8) controlPoint2: CGPointMake(2.93, 8.96)];
    [bezierPath addCurveToPoint: CGPointMake(3.06, 8.69) controlPoint1: CGPointMake(2.93, 8.96) controlPoint2: CGPointMake(3.06, 8.69)];
    [bezierPath addCurveToPoint: CGPointMake(3.42, 7.97) controlPoint1: CGPointMake(3.17, 8.44) controlPoint2: CGPointMake(3.29, 8.2)];
    [bezierPath addCurveToPoint: CGPointMake(4.28, 8.47) controlPoint1: CGPointMake(3.42, 7.97) controlPoint2: CGPointMake(3.5, 8.02)];
    [bezierPath addCurveToPoint: CGPointMake(4.53, 8.03) controlPoint1: CGPointMake(4.36, 8.32) controlPoint2: CGPointMake(4.45, 8.18)];
    [bezierPath addCurveToPoint: CGPointMake(3.67, 7.53) controlPoint1: CGPointMake(4, 7.73) controlPoint2: CGPointMake(3.68, 7.54)];
    [bezierPath addCurveToPoint: CGPointMake(3.44, 7.93) controlPoint1: CGPointMake(3.64, 7.59) controlPoint2: CGPointMake(3.49, 7.84)];
    [bezierPath addCurveToPoint: CGPointMake(3.66, 7.54) controlPoint1: CGPointMake(3.51, 7.8) controlPoint2: CGPointMake(3.58, 7.67)];
    [bezierPath addCurveToPoint: CGPointMake(4.11, 6.86) controlPoint1: CGPointMake(3.81, 7.3) controlPoint2: CGPointMake(3.95, 7.08)];
    [bezierPath addCurveToPoint: CGPointMake(4.51, 7.16) controlPoint1: CGPointMake(4.11, 6.87) controlPoint2: CGPointMake(4.26, 6.97)];
    [bezierPath addCurveToPoint: CGPointMake(4.69, 6.91) controlPoint1: CGPointMake(4.57, 7.07) controlPoint2: CGPointMake(4.63, 6.99)];
    [bezierPath addCurveToPoint: CGPointMake(4.29, 6.62) controlPoint1: CGPointMake(4.43, 6.72) controlPoint2: CGPointMake(4.28, 6.62)];
    [bezierPath addCurveToPoint: CGPointMake(4.85, 5.92) controlPoint1: CGPointMake(4.47, 6.38) controlPoint2: CGPointMake(4.66, 6.14)];
    [bezierPath addCurveToPoint: CGPointMake(5.23, 6.25) controlPoint1: CGPointMake(4.87, 5.93) controlPoint2: CGPointMake(5, 6.05)];
    [bezierPath addCurveToPoint: CGPointMake(5.43, 6.03) controlPoint1: CGPointMake(5.29, 6.18) controlPoint2: CGPointMake(5.36, 6.1)];
    [bezierPath addCurveToPoint: CGPointMake(5.06, 5.69) controlPoint1: CGPointMake(5.24, 5.86) controlPoint2: CGPointMake(5.12, 5.75)];
    [bezierPath addCurveToPoint: CGPointMake(5.69, 5.05) controlPoint1: CGPointMake(5.26, 5.47) controlPoint2: CGPointMake(5.47, 5.26)];
    [bezierPath addCurveToPoint: CGPointMake(6.03, 5.43) controlPoint1: CGPointMake(5.71, 5.07) controlPoint2: CGPointMake(5.82, 5.2)];
    [bezierPath addCurveToPoint: CGPointMake(6.25, 5.23) controlPoint1: CGPointMake(6.1, 5.36) controlPoint2: CGPointMake(6.18, 5.29)];
    [bezierPath addCurveToPoint: CGPointMake(6.1, 5.06) controlPoint1: CGPointMake(6.2, 5.16) controlPoint2: CGPointMake(6.15, 5.11)];
    [bezierPath addCurveToPoint: CGPointMake(5.92, 4.85) controlPoint1: CGPointMake(5.98, 4.93) controlPoint2: CGPointMake(5.92, 4.85)];
    [bezierPath addCurveToPoint: CGPointMake(5.76, 5) controlPoint1: CGPointMake(5.92, 4.85) controlPoint2: CGPointMake(5.82, 4.94)];
    [bezierPath addLineToPoint: CGPointMake(5.92, 4.85)];
    [bezierPath addCurveToPoint: CGPointMake(6.62, 4.28) controlPoint1: CGPointMake(6.14, 4.66) controlPoint2: CGPointMake(6.38, 4.47)];
    [bezierPath addCurveToPoint: CGPointMake(6.91, 4.69) controlPoint1: CGPointMake(6.63, 4.29) controlPoint2: CGPointMake(6.73, 4.44)];
    [bezierPath addCurveToPoint: CGPointMake(7.16, 4.51) controlPoint1: CGPointMake(6.99, 4.63) controlPoint2: CGPointMake(7.07, 4.57)];
    [bezierPath addCurveToPoint: CGPointMake(6.86, 4.11) controlPoint1: CGPointMake(6.97, 4.25) controlPoint2: CGPointMake(6.86, 4.11)];
    [bezierPath addCurveToPoint: CGPointMake(7.34, 3.79) controlPoint1: CGPointMake(7.02, 4) controlPoint2: CGPointMake(7.18, 3.89)];
    [bezierPath addCurveToPoint: CGPointMake(7.92, 3.44) controlPoint1: CGPointMake(7.53, 3.67) controlPoint2: CGPointMake(7.72, 3.55)];
    [bezierPath addCurveToPoint: CGPointMake(7.53, 3.67) controlPoint1: CGPointMake(7.81, 3.51) controlPoint2: CGPointMake(7.53, 3.67)];
    [bezierPath addCurveToPoint: CGPointMake(8.03, 4.53) controlPoint1: CGPointMake(7.55, 3.7) controlPoint2: CGPointMake(7.74, 4.03)];
    [bezierPath addLineToPoint: CGPointMake(8.2, 4.43)];
    [bezierPath addCurveToPoint: CGPointMake(8.47, 4.28) controlPoint1: CGPointMake(8.29, 4.38) controlPoint2: CGPointMake(8.38, 4.33)];
    [bezierPath addCurveToPoint: CGPointMake(7.97, 3.42) controlPoint1: CGPointMake(8.3, 4) controlPoint2: CGPointMake(8.14, 3.71)];
    [bezierPath addCurveToPoint: CGPointMake(8.67, 3.06) controlPoint1: CGPointMake(8.2, 3.29) controlPoint2: CGPointMake(8.43, 3.17)];
    [bezierPath addCurveToPoint: CGPointMake(8.95, 2.93) controlPoint1: CGPointMake(8.76, 3.02) controlPoint2: CGPointMake(8.86, 2.98)];
    [bezierPath addLineToPoint: CGPointMake(9.8, 2.61)];
    [bezierPath addCurveToPoint: CGPointMake(10.09, 2.52) controlPoint1: CGPointMake(9.8, 2.61) controlPoint2: CGPointMake(10.09, 2.52)];
    [bezierPath addCurveToPoint: CGPointMake(10.96, 2.28) controlPoint1: CGPointMake(10.09, 2.51) controlPoint2: CGPointMake(10.96, 2.28)];
    [bezierPath addCurveToPoint: CGPointMake(11.26, 2.22) controlPoint1: CGPointMake(10.96, 2.28) controlPoint2: CGPointMake(11.26, 2.22)];
    [bezierPath addCurveToPoint: CGPointMake(12.15, 2.08) controlPoint1: CGPointMake(11.55, 2.16) controlPoint2: CGPointMake(11.85, 2.11)];
    [bezierPath addLineToPoint: CGPointMake(12.38, 2.05)];
    [bezierPath addLineToPoint: CGPointMake(13.22, 2)];
    [bezierPath addLineToPoint: CGPointMake(13.5, 2)];
    [bezierPath addLineToPoint: CGPointMake(13.61, 2)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(6.85, 4.11)];
    [bezierPath addCurveToPoint: CGPointMake(6.66, 4.25) controlPoint1: CGPointMake(6.79, 4.16) controlPoint2: CGPointMake(6.71, 4.22)];
    [bezierPath addLineToPoint: CGPointMake(6.83, 4.13)];
    [bezierPath addLineToPoint: CGPointMake(6.85, 4.11)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(4.27, 6.64)];
    [bezierPath addCurveToPoint: CGPointMake(4.12, 6.85) controlPoint1: CGPointMake(4.22, 6.71) controlPoint2: CGPointMake(4.15, 6.81)];
    [bezierPath addLineToPoint: CGPointMake(4.26, 6.65)];
    [bezierPath addLineToPoint: CGPointMake(4.27, 6.64)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(23.38, 7.62)];
    [bezierPath addCurveToPoint: CGPointMake(23.54, 7.9) controlPoint1: CGPointMake(23.44, 7.71) controlPoint2: CGPointMake(23.49, 7.8)];
    [bezierPath addCurveToPoint: CGPointMake(23.38, 7.62) controlPoint1: CGPointMake(23.5, 7.82) controlPoint2: CGPointMake(23.43, 7.7)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(3.06, 8.69)];
    [bezierPath addLineToPoint: CGPointMake(2.93, 8.96)];
    [bezierPath addCurveToPoint: CGPointMake(3.39, 9.16) controlPoint1: CGPointMake(2.93, 8.96) controlPoint2: CGPointMake(3.09, 9.03)];
    [bezierPath addCurveToPoint: CGPointMake(3.51, 8.89) controlPoint1: CGPointMake(3.43, 9.07) controlPoint2: CGPointMake(3.47, 8.98)];
    [bezierPath addCurveToPoint: CGPointMake(3.06, 8.69) controlPoint1: CGPointMake(3.22, 8.76) controlPoint2: CGPointMake(3.06, 8.69)];
    [bezierPath addLineToPoint: CGPointMake(3.06, 8.69)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(23.94, 8.69)];
    [bezierPath addCurveToPoint: CGPointMake(23.49, 8.89) controlPoint1: CGPointMake(23.94, 8.69) controlPoint2: CGPointMake(23.78, 8.76)];
    [bezierPath addCurveToPoint: CGPointMake(23.61, 9.16) controlPoint1: CGPointMake(23.53, 8.98) controlPoint2: CGPointMake(23.57, 9.07)];
    [bezierPath addCurveToPoint: CGPointMake(24.07, 8.96) controlPoint1: CGPointMake(23.91, 9.03) controlPoint2: CGPointMake(24.07, 8.96)];
    [bezierPath addCurveToPoint: CGPointMake(23.95, 8.69) controlPoint1: CGPointMake(24.07, 8.96) controlPoint2: CGPointMake(23.94, 8.69)];
    [bezierPath addLineToPoint: CGPointMake(23.94, 8.69)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(2.61, 9.8)];
    [bezierPath addLineToPoint: CGPointMake(2.52, 10.09)];
    [bezierPath addCurveToPoint: CGPointMake(2.99, 10.24) controlPoint1: CGPointMake(2.52, 10.09) controlPoint2: CGPointMake(2.68, 10.14)];
    [bezierPath addCurveToPoint: CGPointMake(3.08, 9.96) controlPoint1: CGPointMake(3.02, 10.15) controlPoint2: CGPointMake(3.05, 10.05)];
    [bezierPath addCurveToPoint: CGPointMake(2.61, 9.8) controlPoint1: CGPointMake(2.78, 9.86) controlPoint2: CGPointMake(2.61, 9.8)];
    [bezierPath addLineToPoint: CGPointMake(2.61, 9.8)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(24.37, 9.81)];
    [bezierPath addCurveToPoint: CGPointMake(23.92, 9.96) controlPoint1: CGPointMake(24.32, 9.83) controlPoint2: CGPointMake(24.16, 9.88)];
    [bezierPath addCurveToPoint: CGPointMake(24.01, 10.24) controlPoint1: CGPointMake(23.95, 10.05) controlPoint2: CGPointMake(23.98, 10.15)];
    [bezierPath addCurveToPoint: CGPointMake(24.48, 10.09) controlPoint1: CGPointMake(24.32, 10.14) controlPoint2: CGPointMake(24.48, 10.09)];
    [bezierPath addCurveToPoint: CGPointMake(24.38, 9.81) controlPoint1: CGPointMake(24.48, 10.09) controlPoint2: CGPointMake(24.39, 9.8)];
    [bezierPath addLineToPoint: CGPointMake(24.37, 9.81)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(2.28, 10.96)];
    [bezierPath addLineToPoint: CGPointMake(2.22, 11.26)];
    [bezierPath addCurveToPoint: CGPointMake(2.71, 11.36) controlPoint1: CGPointMake(2.22, 11.26) controlPoint2: CGPointMake(2.39, 11.29)];
    [bezierPath addCurveToPoint: CGPointMake(2.77, 11.07) controlPoint1: CGPointMake(2.73, 11.26) controlPoint2: CGPointMake(2.75, 11.16)];
    [bezierPath addCurveToPoint: CGPointMake(2.28, 10.96) controlPoint1: CGPointMake(2.46, 11) controlPoint2: CGPointMake(2.28, 10.96)];
    [bezierPath addLineToPoint: CGPointMake(2.28, 10.96)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(24.7, 10.97)];
    [bezierPath addCurveToPoint: CGPointMake(24.23, 11.07) controlPoint1: CGPointMake(24.64, 10.98) controlPoint2: CGPointMake(24.48, 11.01)];
    [bezierPath addCurveToPoint: CGPointMake(24.29, 11.36) controlPoint1: CGPointMake(24.25, 11.16) controlPoint2: CGPointMake(24.27, 11.26)];
    [bezierPath addCurveToPoint: CGPointMake(24.78, 11.26) controlPoint1: CGPointMake(24.61, 11.29) controlPoint2: CGPointMake(24.78, 11.26)];
    [bezierPath addCurveToPoint: CGPointMake(24.7, 10.97) controlPoint1: CGPointMake(24.78, 11.26) controlPoint2: CGPointMake(24.72, 10.96)];
    [bezierPath addLineToPoint: CGPointMake(24.7, 10.97)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(22.15, 7.78)];
    [bezierPath addCurveToPoint: CGPointMake(21.18, 8.13) controlPoint1: CGPointMake(21.84, 7.9) controlPoint2: CGPointMake(21.18, 8.13)];
    [bezierPath addCurveToPoint: CGPointMake(14.65, 12.54) controlPoint1: CGPointMake(21.18, 8.13) controlPoint2: CGPointMake(16.9, 11.02)];
    [bezierPath addCurveToPoint: CGPointMake(13.48, 12) controlPoint1: CGPointMake(14.38, 12.21) controlPoint2: CGPointMake(13.96, 12)];
    [bezierPath addCurveToPoint: CGPointMake(12.13, 12.89) controlPoint1: CGPointMake(12.88, 12.01) controlPoint2: CGPointMake(12.36, 12.37)];
    [bezierPath addCurveToPoint: CGPointMake(6.96, 12.07) controlPoint1: CGPointMake(10.26, 12.59) controlPoint2: CGPointMake(6.96, 12.07)];
    [bezierPath addLineToPoint: CGPointMake(5.9, 12.4)];
    [bezierPath addLineToPoint: CGPointMake(6.81, 13.05)];
    [bezierPath addCurveToPoint: CGPointMake(12.05, 13.89) controlPoint1: CGPointMake(6.81, 13.05) controlPoint2: CGPointMake(10.2, 13.59)];
    [bezierPath addCurveToPoint: CGPointMake(13.5, 15) controlPoint1: CGPointMake(12.22, 14.53) controlPoint2: CGPointMake(12.8, 15)];
    [bezierPath addCurveToPoint: CGPointMake(15, 13.5) controlPoint1: CGPointMake(14.33, 15) controlPoint2: CGPointMake(15, 14.33)];
    [bezierPath addCurveToPoint: CGPointMake(14.9, 12.97) controlPoint1: CGPointMake(15, 13.31) controlPoint2: CGPointMake(14.97, 13.14)];
    [bezierPath addCurveToPoint: CGPointMake(21.46, 8.55) controlPoint1: CGPointMake(17.15, 11.46) controlPoint2: CGPointMake(21.46, 8.55)];
    [bezierPath addCurveToPoint: CGPointMake(22.12, 7.82) controlPoint1: CGPointMake(21.46, 8.55) controlPoint2: CGPointMake(21.97, 7.99)];
    [bezierPath addLineToPoint: CGPointMake(22.15, 7.78)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(24.29, 15.64)];
    [bezierPath addCurveToPoint: CGPointMake(24.23, 15.93) controlPoint1: CGPointMake(24.27, 15.74) controlPoint2: CGPointMake(24.25, 15.84)];
    [bezierPath addCurveToPoint: CGPointMake(24.72, 16.04) controlPoint1: CGPointMake(24.54, 16) controlPoint2: CGPointMake(24.72, 16.04)];
    [bezierPath addCurveToPoint: CGPointMake(24.75, 15.74) controlPoint1: CGPointMake(24.72, 16.04) controlPoint2: CGPointMake(24.78, 15.74)];
    [bezierPath addCurveToPoint: CGPointMake(24.29, 15.64) controlPoint1: CGPointMake(24.68, 15.72) controlPoint2: CGPointMake(24.53, 15.69)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(2.71, 15.64)];
    [bezierPath addCurveToPoint: CGPointMake(2.22, 15.74) controlPoint1: CGPointMake(2.39, 15.71) controlPoint2: CGPointMake(2.22, 15.74)];
    [bezierPath addLineToPoint: CGPointMake(2.28, 16.04)];
    [bezierPath addCurveToPoint: CGPointMake(2.77, 15.93) controlPoint1: CGPointMake(2.28, 16.04) controlPoint2: CGPointMake(2.46, 16)];
    [bezierPath addCurveToPoint: CGPointMake(2.71, 15.64) controlPoint1: CGPointMake(2.75, 15.84) controlPoint2: CGPointMake(2.73, 15.74)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(24.01, 16.76)];
    [bezierPath addCurveToPoint: CGPointMake(23.92, 17.04) controlPoint1: CGPointMake(23.98, 16.85) controlPoint2: CGPointMake(23.95, 16.95)];
    [bezierPath addCurveToPoint: CGPointMake(24.39, 17.2) controlPoint1: CGPointMake(24.22, 17.14) controlPoint2: CGPointMake(24.39, 17.2)];
    [bezierPath addCurveToPoint: CGPointMake(24.45, 16.9) controlPoint1: CGPointMake(24.39, 17.2) controlPoint2: CGPointMake(24.48, 16.91)];
    [bezierPath addCurveToPoint: CGPointMake(24.01, 16.76) controlPoint1: CGPointMake(24.39, 16.88) controlPoint2: CGPointMake(24.24, 16.83)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(2.99, 16.76)];
    [bezierPath addCurveToPoint: CGPointMake(2.52, 16.91) controlPoint1: CGPointMake(2.68, 16.86) controlPoint2: CGPointMake(2.52, 16.91)];
    [bezierPath addLineToPoint: CGPointMake(2.61, 17.2)];
    [bezierPath addCurveToPoint: CGPointMake(3.08, 17.04) controlPoint1: CGPointMake(2.61, 17.2) controlPoint2: CGPointMake(2.78, 17.14)];
    [bezierPath addCurveToPoint: CGPointMake(2.99, 16.76) controlPoint1: CGPointMake(3.05, 16.95) controlPoint2: CGPointMake(3.02, 16.85)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(23.61, 17.84)];
    [bezierPath addCurveToPoint: CGPointMake(23.49, 18.11) controlPoint1: CGPointMake(23.57, 17.93) controlPoint2: CGPointMake(23.53, 18.02)];
    [bezierPath addCurveToPoint: CGPointMake(23.94, 18.31) controlPoint1: CGPointMake(23.78, 18.24) controlPoint2: CGPointMake(23.94, 18.31)];
    [bezierPath addCurveToPoint: CGPointMake(24.04, 18.03) controlPoint1: CGPointMake(23.94, 18.31) controlPoint2: CGPointMake(24.07, 18.04)];
    [bezierPath addCurveToPoint: CGPointMake(23.61, 17.84) controlPoint1: CGPointMake(23.98, 18) controlPoint2: CGPointMake(23.83, 17.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(3.39, 17.84)];
    [bezierPath addCurveToPoint: CGPointMake(2.93, 18.04) controlPoint1: CGPointMake(3.09, 17.97) controlPoint2: CGPointMake(2.93, 18.04)];
    [bezierPath addLineToPoint: CGPointMake(3.06, 18.31)];
    [bezierPath addCurveToPoint: CGPointMake(3.51, 18.11) controlPoint1: CGPointMake(3.06, 18.31) controlPoint2: CGPointMake(3.22, 18.24)];
    [bezierPath addCurveToPoint: CGPointMake(3.39, 17.84) controlPoint1: CGPointMake(3.47, 18.02) controlPoint2: CGPointMake(3.43, 17.93)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(3.43, 19.06)];
    [bezierPath addCurveToPoint: CGPointMake(3.62, 19.38) controlPoint1: CGPointMake(3.5, 19.18) controlPoint2: CGPointMake(3.57, 19.3)];
    [bezierPath addCurveToPoint: CGPointMake(3.46, 19.1) controlPoint1: CGPointMake(3.56, 19.29) controlPoint2: CGPointMake(3.51, 19.2)];
    [bezierPath addLineToPoint: CGPointMake(3.43, 19.06)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(23.55, 19.01)];
    [bezierPath addCurveToPoint: CGPointMake(23.36, 19.42) controlPoint1: CGPointMake(23.51, 19.16) controlPoint2: CGPointMake(23.44, 19.29)];
    [bezierPath addCurveToPoint: CGPointMake(23.55, 19.01) controlPoint1: CGPointMake(23.43, 19.3) controlPoint2: CGPointMake(23.58, 19.03)];
    [bezierPath addLineToPoint: CGPointMake(23.55, 19.01)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(4.11, 20.14)];
    [bezierPath addCurveToPoint: CGPointMake(4.19, 20.25) controlPoint1: CGPointMake(4.13, 20.17) controlPoint2: CGPointMake(4.16, 20.21)];
    [bezierPath addCurveToPoint: CGPointMake(4.28, 20.38) controlPoint1: CGPointMake(4.24, 20.32) controlPoint2: CGPointMake(4.28, 20.38)];
    [bezierPath addLineToPoint: CGPointMake(4.19, 20.26)];
    [bezierPath addLineToPoint: CGPointMake(4.12, 20.15)];
    [bezierPath addLineToPoint: CGPointMake(4.11, 20.14)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(22.87, 20.12)];
    [bezierPath addLineToPoint: CGPointMake(22.73, 20.36)];
    [bezierPath addCurveToPoint: CGPointMake(22.87, 20.12) controlPoint1: CGPointMake(22.78, 20.3) controlPoint2: CGPointMake(22.89, 20.13)];
    [bezierPath addLineToPoint: CGPointMake(22.87, 20.12)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(22.12, 21.06)];
    [bezierPath addLineToPoint: CGPointMake(21.98, 21.26)];
    [bezierPath addCurveToPoint: CGPointMake(22.12, 21.06) controlPoint1: CGPointMake(22.04, 21.2) controlPoint2: CGPointMake(22.14, 21.08)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(21.29, 21.92)];
    [bezierPath addLineToPoint: CGPointMake(21.13, 22.1)];
    [bezierPath addCurveToPoint: CGPointMake(21.29, 21.92) controlPoint1: CGPointMake(21.2, 22.04) controlPoint2: CGPointMake(21.3, 21.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(6.66, 22.74)];
    [bezierPath addCurveToPoint: CGPointMake(6.75, 22.81) controlPoint1: CGPointMake(6.62, 22.72) controlPoint2: CGPointMake(6.68, 22.76)];
    [bezierPath addCurveToPoint: CGPointMake(6.85, 22.88) controlPoint1: CGPointMake(6.79, 22.84) controlPoint2: CGPointMake(6.83, 22.87)];
    [bezierPath addLineToPoint: CGPointMake(6.74, 22.81)];
    [bezierPath addLineToPoint: CGPointMake(6.65, 22.74)];
    [bezierPath addLineToPoint: CGPointMake(6.66, 22.74)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(20.36, 22.69)];
    [bezierPath addLineToPoint: CGPointMake(20.15, 22.89)];
    [bezierPath addCurveToPoint: CGPointMake(20.36, 22.69) controlPoint1: CGPointMake(20.19, 22.85) controlPoint2: CGPointMake(20.38, 22.71)];
    [bezierPath addLineToPoint: CGPointMake(20.36, 22.69)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(7.58, 23.36)];
    [bezierPath addCurveToPoint: CGPointMake(7.9, 23.54) controlPoint1: CGPointMake(7.7, 23.43) controlPoint2: CGPointMake(7.82, 23.5)];
    [bezierPath addCurveToPoint: CGPointMake(7.62, 23.38) controlPoint1: CGPointMake(7.8, 23.49) controlPoint2: CGPointMake(7.71, 23.44)];
    [bezierPath addLineToPoint: CGPointMake(7.58, 23.36)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(19.45, 23.3)];
    [bezierPath addCurveToPoint: CGPointMake(19.08, 23.56) controlPoint1: CGPointMake(19.34, 23.41) controlPoint2: CGPointMake(19.21, 23.48)];
    [bezierPath addCurveToPoint: CGPointMake(19.45, 23.3) controlPoint1: CGPointMake(19.19, 23.49) controlPoint2: CGPointMake(19.46, 23.33)];
    [bezierPath addLineToPoint: CGPointMake(19.45, 23.3)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(18.11, 23.49)];
    [bezierPath addCurveToPoint: CGPointMake(17.84, 23.61) controlPoint1: CGPointMake(18.02, 23.53) controlPoint2: CGPointMake(17.93, 23.57)];
    [bezierPath addCurveToPoint: CGPointMake(18.04, 24.07) controlPoint1: CGPointMake(17.97, 23.91) controlPoint2: CGPointMake(18.04, 24.07)];
    [bezierPath addCurveToPoint: CGPointMake(18.3, 23.91) controlPoint1: CGPointMake(18.04, 24.07) controlPoint2: CGPointMake(18.31, 23.94)];
    [bezierPath addCurveToPoint: CGPointMake(18.11, 23.49) controlPoint1: CGPointMake(18.27, 23.86) controlPoint2: CGPointMake(18.21, 23.71)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(8.89, 23.49)];
    [bezierPath addCurveToPoint: CGPointMake(8.69, 23.94) controlPoint1: CGPointMake(8.76, 23.78) controlPoint2: CGPointMake(8.69, 23.94)];
    [bezierPath addLineToPoint: CGPointMake(8.96, 24.07)];
    [bezierPath addCurveToPoint: CGPointMake(9.16, 23.61) controlPoint1: CGPointMake(8.96, 24.07) controlPoint2: CGPointMake(9.03, 23.91)];
    [bezierPath addCurveToPoint: CGPointMake(8.89, 23.49) controlPoint1: CGPointMake(9.07, 23.57) controlPoint2: CGPointMake(8.98, 23.53)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(17.04, 23.92)];
    [bezierPath addCurveToPoint: CGPointMake(16.76, 24.01) controlPoint1: CGPointMake(16.95, 23.95) controlPoint2: CGPointMake(16.85, 23.98)];
    [bezierPath addCurveToPoint: CGPointMake(16.91, 24.48) controlPoint1: CGPointMake(16.86, 24.32) controlPoint2: CGPointMake(16.91, 24.48)];
    [bezierPath addCurveToPoint: CGPointMake(17.19, 24.36) controlPoint1: CGPointMake(16.91, 24.48) controlPoint2: CGPointMake(17.2, 24.39)];
    [bezierPath addCurveToPoint: CGPointMake(17.04, 23.92) controlPoint1: CGPointMake(17.17, 24.3) controlPoint2: CGPointMake(17.12, 24.15)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(9.96, 23.92)];
    [bezierPath addCurveToPoint: CGPointMake(9.8, 24.39) controlPoint1: CGPointMake(9.86, 24.22) controlPoint2: CGPointMake(9.8, 24.39)];
    [bezierPath addLineToPoint: CGPointMake(10.09, 24.48)];
    [bezierPath addCurveToPoint: CGPointMake(10.24, 24.01) controlPoint1: CGPointMake(10.09, 24.48) controlPoint2: CGPointMake(10.14, 24.32)];
    [bezierPath addCurveToPoint: CGPointMake(9.96, 23.92) controlPoint1: CGPointMake(10.15, 23.98) controlPoint2: CGPointMake(10.05, 23.95)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(15.93, 24.23)];
    [bezierPath addCurveToPoint: CGPointMake(15.64, 24.29) controlPoint1: CGPointMake(15.84, 24.25) controlPoint2: CGPointMake(15.74, 24.27)];
    [bezierPath addCurveToPoint: CGPointMake(15.74, 24.78) controlPoint1: CGPointMake(15.71, 24.61) controlPoint2: CGPointMake(15.74, 24.78)];
    [bezierPath addCurveToPoint: CGPointMake(16.03, 24.69) controlPoint1: CGPointMake(15.74, 24.78) controlPoint2: CGPointMake(16.04, 24.72)];
    [bezierPath addCurveToPoint: CGPointMake(15.93, 24.23) controlPoint1: CGPointMake(16.02, 24.62) controlPoint2: CGPointMake(15.98, 24.47)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(11.07, 24.23)];
    [bezierPath addCurveToPoint: CGPointMake(10.96, 24.72) controlPoint1: CGPointMake(11, 24.54) controlPoint2: CGPointMake(10.96, 24.72)];
    [bezierPath addLineToPoint: CGPointMake(11.26, 24.78)];
    [bezierPath addCurveToPoint: CGPointMake(11.36, 24.29) controlPoint1: CGPointMake(11.26, 24.78) controlPoint2: CGPointMake(11.29, 24.61)];
    [bezierPath addCurveToPoint: CGPointMake(11.07, 24.23) controlPoint1: CGPointMake(11.26, 24.27) controlPoint2: CGPointMake(11.16, 24.25)];
    [bezierPath closePath];
    [color0 setFill];
    [bezierPath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfAlarmClockIcon
{
    if (_imageOfAlarmClockIcon)
        return _imageOfAlarmClockIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(28, 27), NO, 0.0f);
    [PaintCodeStyleKit drawAlarmClockIcon];

    _imageOfAlarmClockIcon = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfAlarmClockIcon;
}

+ (UIImage*)imageOfLetterTIcon
{
    if (_imageOfLetterTIcon)
        return _imageOfLetterTIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(13, 17), NO, 0.0f);
    [PaintCodeStyleKit drawLetterTIcon];

    _imageOfLetterTIcon = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfLetterTIcon;
}

+ (UIImage*)imageOfAddIcon
{
    if (_imageOfAddIcon)
        return _imageOfAddIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(17, 17), NO, 0.0f);
    [PaintCodeStyleKit drawAddIcon];

    _imageOfAddIcon = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfAddIcon;
}

+ (UIImage*)imageOfArrow
{
    if (_imageOfArrow)
        return _imageOfArrow;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(20, 80), NO, 0.0f);
    [PaintCodeStyleKit drawArrow];

    _imageOfArrow = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfArrow;
}

+ (UIImage*)imageOfClock
{
    if (_imageOfClock)
        return _imageOfClock;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(27, 27), NO, 0.0f);
    [PaintCodeStyleKit drawClock];

    _imageOfClock = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfClock;
}

#pragma mark Customization Infrastructure

- (void)setAlarmClockIconTargets: (NSArray*)alarmClockIconTargets
{
    _alarmClockIconTargets = alarmClockIconTargets;

    for (id target in self.alarmClockIconTargets)
        [target setImage: PaintCodeStyleKit.imageOfAlarmClockIcon];
}

- (void)setLetterTIconTargets: (NSArray*)letterTIconTargets
{
    _letterTIconTargets = letterTIconTargets;

    for (id target in self.letterTIconTargets)
        [target setImage: PaintCodeStyleKit.imageOfLetterTIcon];
}

- (void)setAddIconTargets: (NSArray*)addIconTargets
{
    _addIconTargets = addIconTargets;

    for (id target in self.addIconTargets)
        [target setImage: PaintCodeStyleKit.imageOfAddIcon];
}

- (void)setArrowTargets: (NSArray*)arrowTargets
{
    _arrowTargets = arrowTargets;

    for (id target in self.arrowTargets)
        [target setImage: PaintCodeStyleKit.imageOfArrow];
}

- (void)setClockTargets: (NSArray*)clockTargets
{
    _clockTargets = clockTargets;

    for (id target in self.clockTargets)
        [target setImage: PaintCodeStyleKit.imageOfClock];
}


@end
