//
//  PaintCodeStyleKit.h
//  Tackle
//
//  Created by Scott Bader on 1/3/15.
//  Copyright (c) 2015 Melody Road, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* alarmClockIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* letterTIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* arrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* clockTargets;

// Generated Images
+ (UIImage*)imageOfAlarmClockIcon;
+ (UIImage*)imageOfLetterTIcon;
+ (UIImage*)imageOfAddIcon;
+ (UIImage*)imageOfArrow;
+ (UIImage*)imageOfClock;

@end
